// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translation

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"change password failed":                           4,
	"change password sussessfully":                     5,
	"create user %s sussessfully":                      9,
	"delete user sussessfully":                         10,
	"list license failed":                              0,
	"list tokens failed":                               11,
	"list users failed":                                6,
	"login successfully":                               7,
	"logout successfully":                              8,
	"password confirmation doesn't match the password": 2,
	"user does not exist":                              1,
	"user password verify failed":                      3,
}

var en_USIndex = []uint32{ // 13 elements
	0x00000000, 0x00000014, 0x00000028, 0x00000059,
	0x00000075, 0x0000008c, 0x000000a9, 0x000000bb,
	0x000000ce, 0x000000e2, 0x00000101, 0x0000011a,
	0x0000012d,
} // Size: 76 bytes

const en_USData string = "" + // Size: 301 bytes
	"\x02list license failed\x02user does not exist\x02password confirmation " +
	"doesn't match the password\x02user password verify failed\x02change pass" +
	"word failed\x02change password sussessfully\x02list users failed\x02logi" +
	"n successfully\x02logout successfully\x02create user %[1]s sussessfully" +
	"\x02delete user sussessfully\x02list tokens failed"

var zh_CNIndex = []uint32{ // 13 elements
	0x00000000, 0x0000001a, 0x0000002a, 0x00000049,
	0x00000062, 0x00000075, 0x00000088, 0x000000a1,
	0x000000ae, 0x000000c1, 0x000000d9, 0x000000ec,
	0x00000104,
} // Size: 76 bytes

const zh_CNData string = "" + // Size: 260 bytes
	"\x02获取license列表失败\x02用户不存在\x02确认密码与密码不相同\x02用户密码验证失败\x02修改密码失败\x02修改密码成功" +
	"\x02获取用户列表失败\x02登陆成功\x02退出登陆成功\x02创建用户%[1]s成功\x02删除用户成功\x02获取token列表失败"

	// Total table size 713 bytes (0KiB); checksum: EF310BDB
