// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translation

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"change password failed":                           7,
	"change password sussessfully":                     8,
	"create agent failed":                              0,
	"create agent successfully":                        1,
	"create user sussessfully":                         12,
	"delete agent failed":                              2,
	"delete agent successfully":                        3,
	"delete user sussessfully":                         13,
	"list users failed":                                9,
	"login successfully":                               10,
	"logout successfully":                              11,
	"password confirmation doesn't match the password": 5,
	"user not exist":                                   4,
	"user password verify failed":                      6,
}

var en_USIndex = []uint32{ // 15 elements
	0x00000000, 0x00000014, 0x0000002e, 0x00000042,
	0x0000005c, 0x0000006b, 0x0000009c, 0x000000b8,
	0x000000cf, 0x000000ec, 0x000000fe, 0x00000111,
	0x00000125, 0x0000013e, 0x00000157,
} // Size: 84 bytes

const en_USData string = "" + // Size: 343 bytes
	"\x02create agent failed\x02create agent successfully\x02delete agent fai" +
	"led\x02delete agent successfully\x02user not exist\x02password confirmat" +
	"ion doesn't match the password\x02user password verify failed\x02change " +
	"password failed\x02change password sussessfully\x02list users failed\x02" +
	"login successfully\x02logout successfully\x02create user sussessfully" +
	"\x02delete user sussessfully"

var zh_CNIndex = []uint32{ // 15 elements
	0x00000000, 0x00000012, 0x00000024, 0x00000036,
	0x00000048, 0x00000058, 0x0000006b, 0x00000084,
	0x00000097, 0x000000aa, 0x000000c3, 0x000000d0,
	0x000000dd, 0x000000f0, 0x00000103,
} // Size: 84 bytes

const zh_CNData string = "" + // Size: 259 bytes
	"\x02创建agent失败\x02创建agent成功\x02删除agent失败\x02删除agent成功\x02用户不存在\x02新密码不匹配" +
	"\x02用户密码校验失败\x02修改密码失败\x02修改密码成功\x02获取用户列表失败\x02登陆成功\x02登出成功\x02创建用户成功" +
	"\x02删除用户成功"

	// Total table size 770 bytes (0KiB); checksum: D6A58ED
